all:
	gcc 2021TT11139-q.c -o organization
	./organization < input_kara_2.txt > output.txt
	gcc 2021CS.c -o organization_us
	./organization_us < input_kara_2.txt > output_us.txt
clean:
	rm -rf organization
	rm -rf organization_us
