all:
	gcc 2021MT60958-q.c -o aditya
	gcc 2021TT11139-q.c -o jaskaran
	./aditya < text1.txt > aoutput1.txt
	./aditya < text2.txt > aoutput2.txt
	./aditya < text3.txt > aoutput3.txt
	./aditya < text4.txt > aoutput4.txt
	./aditya < text5.txt > aoutput5.txt
	./aditya < text6.txt > aoutput6.txt
	./jaskaran < text1.txt > joutput1.txt
	./jaskaran < text2.txt > joutput2.txt
	./jaskaran < text3.txt > joutput3.txt
	./jaskaran < text4.txt > joutput4.txt
	./jaskaran < text5.txt > joutput5.txt
	./jaskaran < text6.txt > joutput6.txt

clean:
	rm -rf aditya
	rm -rf jaskaran